### ISSUE TITLE
Output Font-family selector (drop down menu) >>

### ISSUE THREAD

**Issue by drhus** [drhus/MomCode#8]
Similer to >> https://r12a.github.io/pickers/russian/ 

ideally next to output and resize slider, and it should affect both 1) output 2) Table

I'm not sure about the fonts on the list, can we use list of all google fonts for example? is there some fonts that already there on all pc/mac/Linux android etc?

**Comment by drhus** [comment]
after introducing the FontAwsome Dictionary, this becomes less priority to have.. the idea was to have the ability to change font-family on output in order to find the font which works for most OS, I'm not sure anymore there is a font would work for all OS & vast majority of Unicode, further discussion on https://github.com/drhus/MomCode/issues/9

**Comment by alexandrtovmach** [comment]
After big research I can summarize ― **We can't fix tofu issue, at all.**

My idea is create dictionary lists only based on 100% crossplatform symbols:
https://tutorialzine.com/2014/12/you-dont-need-icons-here-are-100-unicode-symbols-that-you-can-use
In addition to crossplatform unicode gliphs we can add icon-fonts, like Font Awesome (as you said).

Currently we should deprecate all symbols which are not crossplatformed or we can start using Font Awesome only.

But we should do this as soon as possible because we shouldn't give users/tester ability to create their own lists with not universal gliphs. We should choose approach now, because if we leave it for future it'll be hard to implement...

**Comment by alexandrtovmach** [comment]
So after we decided to use only Font Awesome for icons this issue haven't any sense, right? If we using only FA icons for Momcode, it's a bit confusing users to have option to choose font family, which don't change anything
